### PR TITLE
fix copying lua/* to luadir

### LINKED ISSUE #2: xmake backend will not copy lua code to lua directory `~/.local/share/lua`
### Xmake Version

2.9.4

### Operating System Version and Architecture

NixOS

### Describe Bug

For other backend, they will copy `lua/*` to luarocks's lua path such as `~/.local/share/lua`.
However, xmake only copy `output/lib/*.so` to luarocks's lib path such as `~/.local/lib/lua`.

### Expected Behavior

Like cmake backend. Such as:

```lua
rock_manifest = {
   ["cppinsights.nvim-scm-1.rockspec"] = "c1f48bdca17fa78cd5d3cd378b05271c",
   ftplugin = {
      ["cpp.lua"] = "e27626c1430f38ce6d98e2d092492369"
   },
   lib = {
      ["cppinsights.so"] = "13dbf183489c9e68972b905d9ce481e3"
   },
   lua = {
      cppinsights = {
         ["config.lua"] = "f03e71a515e4542cd8a38ac7a41c0654",
         nvim = {
            ["init.lua"] = "49071491749b746a3fed35a1e3a2db95"
         }
      }
   }
}
```

However, xmake will:

```lua
rock_manifest = {
   after = {
      plugin = {
         ["rime.lua"] = "cadf152f7b5fb43e2a96c8e500297aa0"
      }
   },
   lib = {
      ["rime.so"] = "6fd5e32362b3b68d86d1af39064d52bf"
   },
   ["rime.nvim-scm-1.rockspec"] = "22a0addcf7d0580cecd8c82912b269bf"
}
```

Miss lua directory.

### Project Configuration

Refer https://github.com/Freed-Wu/rime.nvim

### Additional Information and Error Logs

-

### PR DESCRIPTION
**Pull request by Freed-Wu**
Fix #2

* Before adding new features and new modules, please go to issues to submit the relevant feature description first.
* Write good commit messages and use the same coding conventions as the rest of the project.
* Please commit code to dev branch and we will merge into master branch in feature
* Ensure your edited codes with four spaces instead of TAB.

------

* 增加新特性和新模块之前，请先到issues提交相关特性说明，经过讨论评估确认后，再进行相应的代码提交，避免做无用工作。
* 编写友好可读的提交信息，并使用与工程代码相同的代码规范，代码请用4个空格字符代替tab缩进。
* 请提交代码到dev分支，如果通过，我们会在特定时间合并到master分支上。
* 为了规范化提交日志的格式，commit消息，不要用中文，请用英文描述。

### CODE REVIEW

**Comment by waruqi** [comment]
luarock install failed, but I don't know why.

**Comment by Freed-Wu** [comment]
BTW, if rename `src/xmake.lua` to `lua/luarocks/build/xmake.lua`, the modules can be omitted from

```lua
build = {
    type = "builtin",
    modules = {
        ["luarocks.build.xmake"] = "src/xmake.lua"
    },
    copy_directories = {}
}
```

to

```lua
build = {
    type = "builtin",
}
```

**Comment by Freed-Wu** [comment]
And seperate `update *.yml` to another PR may be clearer?

**Comment by Freed-Wu** [comment]
```
Error: Failed cloning git repository.
```

Looks network failure?

**Comment by Freed-Wu** [comment]
There are no any tag about example https://github.com/Freed-Wu/luarocks-build-xmake/blob/lua/rockspecs/example1-1.0-1.rockspec#L5

Whatever, the CI error is unrelated to this PR. I advise to open another issue to solve it.

**Comment by Freed-Wu** [comment]
Any other problem?

**Comment by waruqi** [comment]
Sorry, I forgot it, I will try fix ci in these days.

**Comment by waruqi** [comment]
I have fixed it, but it need xmake dev version.

**Comment by Freed-Wu** [comment]
Can you publish a version after merge this PR in luarocks? 1.3-3 are still before this PR.

**Comment by waruqi** [comment]
try 1.4?

**Pull request merged**
